---
    - name: Installing all required apps for webserver on centos 7
      hosts: all #needs to be modified
      become: yes
      tasks: 

        - name: Install yum utils
          yum:
            name: yum-utils
            state: latest

        - name: enable remi-php74 repository
          shell: yum-config-manager --enable remi-php74
          args:
            creates: /etc/yum.repos.d/centos_o.repo

        - name: Install Apache server
          yum:
            name: httpd
            state: latest

        - name: Instal PHP
          yum:
            name:
              - php
              - php-cli
              - php-mysqlnd
            state: latest

        - name: Install NFS-Client
          yum: 
            name: nfs-utils
            state: latest

        - name: Deleting /var/www/html
          file:
            path: /var/www/html
            state: absent

        - name: Recreate /var/www/html with new permisions
          file: 
            path: /var/www/html
            state: directory
            owner: apache
            group: apache
            mode: 0755
            recurse: yes

        - name: Mounting nfs directory with selinux context
          shell: mount -t nfs 10.0.0.95:/var/nfs_share_dir /var/www/html -o context="system_u:object_r:httpd_sys_content_t:s0"

        - name: edit fstab for permanent mount with selinux context
          lineinfile:
            path: /etc/fstab
            line: 'nfs 10.0.0.95:/var/nfs_shared_dir /var/www/html -o context="system_u:object_r:httpd_sys_content_t:s0"'

        - name: start and enable httpd
          ansible.builtin.systemd:
            name: httpd.service
            state: started
            enabled: yes
            